### ISSUE TITLE
Bug: Model placement off-centre and "Arrange" crashes on elliptic build plate (Cura 5.11+)

### ISSUE THREAD

**Issue by drabels** [Ultimaker/Cura#21474]
### Cura Version

5.12.0 (also reproducible in 5.11.x; works correctly in 5.10.2)

### Operating System

Windows 11

### Printer

FLSun V400 (elliptic build plate, centre-is-zero)

### Reproduction steps

Open Cura 5.12.0 with an FLSun V400 printer profile (or any printer with machine_shape: "elliptic")
Load any STL/3MF model via File → Open
Observe model placement position
Right-click the model → select "Arrange All Models" (or use the toolbar button)

### Actual results

Model is placed off-centre, near the edge of the build plate
Cura crashes with the following traceback:

> Traceback (most recent call last):
>   File "cura\CuraApplication.py", line 1566, in arrangeAllInGrid
>     self._arrangeAll(grid_arrangement = True)
>   File "cura\CuraApplication.py", line 1592, in _arrangeAll
>     if bounding_box is None or bounding_box.width < self._volume.getBoundingBox().width or bounding_box.depth < self._volume.getBoundingBox().depth:
>                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'width'
> self._volume.getBoundingBox() returns None for elliptic build plates.

### Expected results

Model loads centred on the build plate (as it does in Cura 5.10.2)
Arrange positions the model in the centre without crashing

Workaround: Right-click → "Center Selected Model" works correctly.
Regression: Works correctly in Cura 5.10.2 with the same printer definition file (verified identical between versions).

### Add your .zip and screenshots here ⬇️

<img width="1646" height="1392" alt="Image" src="https://github.com/user-attachments/assets/5dac41a5-7a9e-48e8-a523-61bb801b690b" />
<img width="1646" height="1392" alt="Image" src="https://github.com/user-attachments/assets/f2b944fa-1b3e-4e0f-926b-dd3d23075074" />
<img width="1643" height="1392" alt="Image" src="https://github.com/user-attachments/assets/434d684d-14a8-4aa3-8262-bd56feda173b" />

[cura.zip](https://github.com/user-attachments/files/26004229/cura.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm unable to duplicate this behavior.  Import your model and set Cura up as it was.  Use the "File | Save Project" command and then zip the 3mf file and post the zip folder here.  Someone from the Cura team will take a look.

(BTW - in that second image it looks like the model is off the build plate.  If so, it should be striped as it would not print in that location.)

**Comment by drabels** [comment]
Hi Greg,

Thanks for your reply.  I think the problem might be specific to the elliptic bed type, but I might be wrong.

In the second image, it's definitely off the build plate - that's part of the problem.  I load the model in Cura, and it places it there automatically.  The bigger problem occurs when I ask it to "Arrange All Models" - then Cura generates a Crash Report.

BTW, It doesn't matter which model I use.  Here's another example with a calibration cube.

In 5.10.2

<img width="1646" height="1392" alt="Image" src="https://github.com/user-attachments/assets/6e0e0575-46d4-4601-a408-bf5b0100207d" />

In 5.12, upon loading, and then after attempting an arrange.

<img width="1643" height="1392" alt="Image" src="https://github.com/user-attachments/assets/d68c411b-1a46-41e1-8061-937f16b01fc5" />

<img width="1643" height="1392" alt="Image" src="https://github.com/user-attachments/assets/d41a6bf3-3b37-457d-a001-91c58ba7a271" />

The zipped 3mf file.  Thank you for your time!

[FV_xyzCalibration_cube.zip](https://github.com/user-attachments/files/26006139/FV_xyzCalibration_cube.zip)

Regards,

Daniel

**Comment by GregValiant** [comment]
I loaded your 3mf file and I still can't duplicate the problem.  This report will take more Cura "nuts and bolts" knowledge than I bring to the table.

**Comment by HellAholic** [comment]
The build volume is not initializing on your instance of Cura, which could mean either a plugin is interfering with the loading of resources, an AV software is throwing a wrench, or some other sort of data corruption that causes the behavior.
- Updating system drivers might help
- Easiest way to check is to disable any plugins you have installed and see if that resolves the issue
- Next is adding the Cura and CuraEngine and installation folder of the application to AV whitelist if present

If there is no build volume, then the calculation fails. The issue is not connected to the build plate shape.

**Comment by drabels** [comment]
Thanks guys.  For the record - It's a vanilla install.  I am not running any AV (beyond defender that comes with Windows), or any plugins for Cura.  The weird part is that there is no problem with 5.10.2!  I'll have to have a think about what I can do next.

**Comment by HellAholic** [comment]
It might be a race condition for calculating the build volume.
Once Cura has opened, before you load the model, just move the camera around and rotate the build plate.
That should trigger a recalculation for the build volume.
After that if you load the model it should appear in the center of the build plate (with the grid visible) and arrange should function.
Let me know if the workaround above is resolving the issue, if so I think I can make a fix for the next version.

If you're willing to do a bit of testing, I can share a build with you via GDrive

**Comment by drabels** [comment]
Hi - so I tried loading the model, rotating and then zooming back - no dice.  Same crash condition.

Edit: I also tried rotating and zooming back _before_ loading the model - same thing occurred.  Sorry!

<img width="1296" height="1032" alt="Image" src="https://github.com/user-attachments/assets/cc5f39ff-e797-4876-99d9-43766b68bd12" />

**Comment by HellAholic** [comment]
Last two checks would be:
- Add another printer instance of the flsun v400
- Add another printer (Ultimaker S5 for example or Creality Ender 3) and see if it's the same issue

I have a fix that should prevent it from crashing by exiting early. But I don't think it will resolve the underlying issue.
https://drive.google.com/file/d/1laYMthpFeGLEzqixecKB_-6Va1_QLbGr/view?usp=sharing

As a secondary measure, go to the configuration folder paths:
- `%appdata%/cura/5.12`
- `%localappdata%/cura/5.12`

Zip both 5.12 folders in Roaming and Local and send them over, if the trigger is somewhere in the profiles or the configuration, that might give a clue as to how and why.

**Comment by drabels** [comment]
Hi again - a quick update.

I went nuclear on my installs - erased all traces of cura from my appdata folder(s) and uninstalled the programs.  Rebooted the PC, installed 5.12 from scratch and then just setup my printer (v400) from the normal wizards.

Loading a model now, it appears correctly and choosing to arrange results in no crash:

<img width="1643" height="1392" alt="Image" src="https://github.com/user-attachments/assets/6687e1fa-8724-47ec-9726-701e606a7a09" />

So I have to assume *something* about my installation upset the config migration process from 5.10 to 5.11 and 5.12.  I'm content to move on from this, if you guys are.  The bug report might be a useful reference in the future though, you never know!

**Comment by GregValiant** [comment]
Excellent that you got it working.
From this side it still leaves questions.  I would think that since this does not appear to be a widespread problem, that it was indeed local to your machine.
I'll leave the bug label on this for now.  We'll see how @HellAholic wants to handle it.
